#!/bin/bash
# SPDX-License-Identifier: 0BSD
# (c) Hanno Böck, Industry Decarbonization Newsletter
# See also: https://industrydecarbonization.com/docs/unfccc/

for x in $(find -mindepth 1 -maxdepth 1 -type d); do
	# avoid unnecessary metadata, see
	# https://reproducible-builds.org/docs/archives/
	XZ_OPT="-9" tar --sort=name --owner=0 --group=0 --numeric-owner --format=ustar -cJf $x.tar.xz $x
done
